PRAGMA recursive_triggers = OFF;
DROP TRIGGER IF EXISTS CheckGraduate;
DROP TRIGGER IF EXISTS CheckRemove;

CREATE TRIGGER CheckGraduate
AFTER UPDATE ON Highschooler
FOR EACH ROW
WHEN NEW.grade > 12
BEGIN
    DELETE FROM Highschooler WHERE ID = OLD.ID;
    DELETE FROM Friend WHERE ID1 = OLD.ID OR ID2 = OLD.ID;
    DELETE FROM Likes WHERE ID1 = OLD.ID OR ID2 = OLD.ID;
END;

CREATE TRIGGER CheckRemove
AFTER DELETE ON Highschooler
FOR EACH ROW
BEGIN
    DELETE FROM Friend WHERE ID1 = OLD.ID OR ID2 = OLD.ID;
    DELETE FROM Likes WHERE ID1 = OLD.ID OR ID2 = OLD.ID;
END;
